[build-system]
requires = [
  "swig==4.3.0",
  "cmake==3.31.4",
  "setuptools==75.3.0",
  "wheel==0.45.1",
  "pytest==8.3.4",
]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
minversion = "8.3"
filterwarnings = ["error"]  # Treat all warnings as errors
