# -*- Mode: Dockerfile -*-
# Dockerfile for building AlmaLinux-based Python pypi package
#
# Usage:
#
# Copy this template file and replace:
# - `{{ SYSTEM }}` system, ex: manylinux, musllinux
# - `{{ TYPE }}` major glibc version, ex: _2_24, _2_28, _2_34
# - `{{ ARCH }}` architecture, ex:  x86_64, i686
# - `{{ PY_MINORS }}` minor Python3 version numbers, ex: "8 9 10 11 12 13"
# Remove the `.template` suffix from the copy.
#
# Examples
# --------
#
# Generate dockerfile:
#
#     .github/docker/run.sh dockerfile -s manylinux -t _2_28 -a x86_64
#
# Build:
#
#     cd dlite  # cd to DLite root directory
#     docker build -t dlite-manylinux_2_28_x86_64 \
#         -f .github/docker/dockerfiles/Dockerfile-manylinux_2_28_x86_64 .
#
# Run (for debugging):
#
#     docker run --rm -it \
#         --volume $PWD:/io \
#         --user $(id -u):$(id -g) \
#         dlite-manylinux_2_28_x86_64 \
#         /bin/bash
#

# Reference: https://github.com/pypa/manylinux
FROM quay.io/pypa/{{ SYSTEM }}{{ TYPE }}_{{ ARCH }}:latest

COPY requirements*.txt /tmp/

# Enable rpmfusion for additional packages
RUN \
  dnf update -y && \
  dnf install -y epel-release && \
  dnf install -y --skip-broken \
    redland-devel \
    rasqal-devel \
    libcurl-devel \
    libxslt-devel \
    libxml2-devel \
    hdf5-devel && \
  # Unpack static libraries
  # It's necessary to be in /opt/_internal because the internal libraries
  # exist here.
  cd /opt/_internal && \
  tar -Jxvf static-libs-for-embedding-only.tar.xz
  # Filter out challenging packages from requirements_full.txt
  #sed \
  #  -e '/pyarrow/d' \
  #  -e '/tables/d' \
  #  -e '/scikit-image/d' \
  #  -i /tmp/requirements_full.txt && \
    # Install required Python packages

ARG PY_MINORS="{{ PY_MINORS }}"

RUN \
  mkdir -p /ci/pip_cache && \
  for minor in ${PY_MINORS}; do \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache -U pip && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache \
      -r /tmp/requirements.txt \
      -r /tmp/requirements_dev.txt \
      -r /tmp/requirements_wheels.txt \
      -r /tmp/requirements_full.txt; \
  done && \
  rm -rf /ci/pip_cache

COPY .github/docker/run.sh .github/docker/IMAGES.txt /tmp/
