# -*- Mode: Dockerfile -*-
# Dockerfile for building AlmaLinux-based Python pypi package
#
# Copy this template file and replace:
# - `{{ SYSTEM }}` system, ex: manylinux
# - `{{ ARCH }}` architecture, ex: x86_64
# - `{{ PY_MINORS }}` minor Python3 version numbers, ex: "8 9 10 11 12 13"
#
# Examples
# --------
#
# Generate dockerfile:
#
#     .github/docker/mkdockerfile.sh \
#         almalinux \
#         quay.io/pypa/manylinux_2_28_x86_64:latest \
#         "8 9 10 11 12 13 14" \
#         > Dockerfile-manylinux_x86_64 .
#
# Build:
#
#     cd dlite  # cd to DLite root directory
#     docker build -t dlite-manylinux_x86_64 -f Dockerfile-manylinux_x86_64 .
#
# Run (for debugging):
#
#     docker run --rm -it --volume $PWD:/io dlite-manylinux_x86_64 /bin/bash
#

# Reference: https://github.com/pypa/manylinux
FROM quay.io/pypa/manylinux_2_28_{{ ARCH }}:latest

# Enable rpmfusion for additional packages
RUN \
  dnf update -y && \
  dnf install -y epel-release && \
  dnf install -y --skip-broken \
    redland-devel \
    rasqal-devel \
    libcurl-devel \
    libxslt-devel \
    libxml2-devel \
    hdf5-devel && \
  # Unpack static libraries
  # It's necessary to be in /opt/_internal because the internal libraries
  # exist here.
  cd /opt/_internal && \
  tar -Jxvf static-libs-for-embedding-only.tar.xz
  # Filter out challenging packages from requirements_full.txt
  #sed \
  #  -e '/pyarrow/d' \
  #  -e '/tables/d' \
  #  -e '/scikit-image/d' \
  #  -i /tmp/requirements_full.txt && \
    # Install required Python packages

ARG PY_MINORS="{{ PY_MINORS }}"

COPY requirements*.txt /tmp/

RUN \
  mkdir -p /ci/pip_cache && \
  for minor in ${PY_MINORS}; do \
    echo && \
    echo "---------- Python 3.$minor - install requirements ------------" && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache -U pip && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache \
      -r /tmp/requirements.txt \
      -r /tmp/requirements_dev.txt \
      -r /tmp/requirements_full.txt; \
  done && \
  rm -rf /ci/pip_cache

#COPY .github/docker/run.sh .github/docker/IMAGES.txt /tmp/
