# -*- Mode: Dockerfile -*-
# Dockerfile for building CentOS-based Python pypi package
#
# Copy this template file and replace:
# - `{{ SYSTEM }}` system, ex: manylinux
# - `{{ ARCH }}` architecture, ex: i686
# - `{{ PY_MINORS }}` minor Python3 version numbers, ex: "10 11 12 13 14"
#
# Examples
# --------
#
# Generate dockerfile:
#
#     .github/docker/run.sh dockerfile
#
# Build:
#
#     cd dlite  # cd to DLite root directory
#     docker build -t dlite-manylinux_i686 \
#       -f .github/docker/dockerfiles/Dockerfile-manylinux_i686 .
#
# Run (for debugging):
#
#     docker run --rm -it --volume $PWD:/io dlite-manylinux_i686 /bin/bash
#

# Reference: https://github.com/pypa/manylinux
FROM quay.io/pypa/manylinux2014_{{ ARCH }}:latest

# Enable rpmfusion for additional packages
RUN \
  yum update -y && \
  yum localinstall -y --skip-broken \
    https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %centos_ver).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %centos_ver).noarch.rpm && \
  yum install -y --skip-broken \
    redland-devel \
    rasqal-devel \
    libcurl-devel \
    libxslt-devel \
    libxml2-devel && \
    #hdf5-devel && \
  # Unpack static libraries
  # It's necessary to be in /opt/_internal because the internal libraries
  # exist here.
  cd /opt/_internal && \
  tar -Jxvf static-libs-for-embedding-only.tar.xz


# Filter out challenging packages from requirements
COPY requirements*.txt /tmp/
RUN sed \
    -e '/mongomock/d' \
    -i  /tmp/requirements_dev.txt

ARG PY_MINORS="{{ PY_MINORS }}"

RUN \
  mkdir -p /ci/pip_cache && \
  for minor in ${PY_MINORS}; do \
    echo && \
    echo "---------- Python 3.$minor - install requirements ------------" && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache -U pip && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache \
      -r /tmp/requirements.txt \
      -r /tmp/requirements_dev.txt \
  done && \
  rm -rf /ci/pip_cache

#COPY .github/docker/run.sh .github/docker/IMAGES.txt /tmp/
