# -*- Mode: Dockerfile -*-
# Dockerfile for building Python pypi package with Alpine
#
# Copy this template file and replace:
# - `{{ SYSTEM }}` system, ex: musllinux
# - `{{ ARCH }}` architecture, ex: x86_64
# - `{{ BASE_IMAGE }}` base image, ex: quay.io/pypa/musllinux_1_2_x86_64:latest
# - `{{ PY_MINORS }}` minor Python3 version numbers, ex: "10 11 12 13 14"
#
# Examples
# --------
#
# Generate dockerfile:
#
#     .github/docker/mkdockerfile.sh \
#         alpine \
#         quay.io/pypa/musllinux_1_1_x86_64:latest \
#         "8 9 10 11 12 13 14" \
#         > Dockerfile-musllinux_x86_64 .
#
# Build:
#
#     cd dlite  # cd to DLite root directory
#     docker build -t dlite-musllinux_x86_64 -f Dockerfile-musllinux_x86_64 .
#
# Run (for debugging):
#
#     docker run --rm -it --volume $PWD:/io dlite-musllinux_x86_64 /bin/bash
#

# Reference: https://github.com/pypa/manylinux
FROM quay.io/pypa/musllinux_1_2_{{ ARCH }}:latest
#FROM {{ BASE_IMAGE }}

# Do not use distutils distributed with setuptools
# This is due to base changes in the distutils API, removing msvccompiler,
# which is necessary for building the numpy wheel.
#ENV SETUPTOOLS_USE_DISTUTILS="stdlib"

RUN \
  apk add -u \
    redland-dev \
    rasqal-dev \
    hdf5-dev \
    openssl-dev \
    openblas-dev \
    swig \
    rust \
    cargo && \
  # Unpack static libraries
  # It's necessary to be in /opt/_internal because the internal libraries
  # exist here.
  cd /opt/_internal && \
  tar -Jxvf static-libs-for-embedding-only.tar.xz && \
  # Filter out challenging packages from requirements_full.txt
    #-e 's/^pydantic.*/pydantic<2/' \
  sed \
    -e '/pandas/d' \
    -e '/pyarrow/d' \
    -e '/tables/d' \
    -e '/jinja2/d' \
    -e '/pydantic/d' \
    -e '/matplotlib/d' \
    -e '/scikit-image/d' \
    -e '/ncempy/d' \
    -e '/h5py/d' \
    -e '/pymongo/d' \
    -e '/fortran-language-server/d' \
    -i /tmp/requirements_full.txt && \
  sed \
    -e '/mongomock/d' \
    -i /tmp/requirements_dev.txt

COPY requirements*.txt /tmp/

ARG PY_MINORS="{{ PY_MINORS }}"

RUN \
  # Install required Python packages
  mkdir -p /ci/pip_cache && \
  for minor in ${PY_MINORS}; do \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache -U pip && \
    python3.${minor} -m pip install --cache-dir=/ci/pip_cache \
      -r /tmp/requirements.txt \
      -r /tmp/requirements_dev.txt \
      -r /tmp/requirements_wheels.txt \
      -r /tmp/requirements_full.txt; \
  done && \
  rm -rf /ci/pip_cache

#COPY .github/docker/run.sh .github/docker/IMAGES.txt /tmp/
