# This empty package exists for setup.py to not fail on setup(packages = [ "dlite" ])
# The actual dlite Python package will be generated by setup.py using cmake in ./build
# during "python setup.py install"