#ifndef _DLITE_GETLICENSE_H
#define _DLITE_GETLICENSE_H

/* Note that the c file corresponding to this header is generated by
 * the build system. */

/**
  Returns a static pointer to license information of DLite.
 */
const char *dlite_get_license(void);

#endif /* _DLITE_GETLICENSE_H */
