# -*- Mode: Dockerfile -*-
# Dockerfile for test building with minimal requirements on Ubuntu.
#
# This file was added for reproducing DLite issue #711.  It is
# currently not used by the test system, but it is kept here for easy
# checking future Ubuntu-related build issues.
#
# Build:
#
#     docker build -t dlite-ubuntu -f cmake/Dockerfile-ubuntu .
#
# Run:
#
#     docker run --rm -it --volume $PWD:/io dlite-ubuntu /bin/bash
#

FROM ubuntu:latest AS dependencies

SHELL ["/bin/bash", "-c"]

WORKDIR /io

RUN apt-get update --fix-missing
RUN apt-get install -y \
    libhdf5-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv

#    rdflib0-dev

# Create virtual environment
#RUN mkdir /tmp/venv
#RUN python3 -m venv /tmp/venv/dlite
#RUN source /tmp/venv/dlite/bin/activate

# Install Python dependencies
RUN pip3 install -U pip
COPY requirements.txt requirements_dev.txt .
RUN pip3 install -r requirements.txt -r requirements_dev.txt

COPY CMakeLists.txt LICENSE README.md .
COPY python/pyproject.toml python/setup.py
COPY bindings bindings
COPY cmake cmake
COPY doc doc
COPY examples examples
COPY src src
COPY storages storages
COPY tools tools

FROM dependencies AS build
WORKDIR /build
RUN cmake /io -DFORCE_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=/usr/local

FROM build AS install
RUN make install

FROM install AS test
RUN ctest
