name: CD - Deploy documentation to GH Pages

on:
  push:
    branches: ["master"]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  ONTODOC_DIR: doc
  BUILD_DIR: tmp
  PUBLISH_DIR: pages

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install \
            libxml2-dev \
            libxslt-dev \
            libhdf5-dev \
            doxygen \
            graphviz \
            python3 \
            python3-pip \
            python3-dev \
            python3-numpy \
            python3-yaml
          #python3 -m pip install psycopg2-binary==2.9.5

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements_doc.txt -r requirements_dev.txt

      - name: Available version of installed programs
        run: |
          python --version
          swig -version
          cmake -version
          doxygen --version
          dot -V

      - name: Run CMAKE
        run: |
          mkdir -p build
          cd build
          Python3_ROOT=$(python3 -c 'import sys; print(sys.exec_prefix)') \
            CFLAGS='-Wno-missing-field-initializers' \
            cmake .. -DFORCE_EXAMPLES=ON -DWITH_DOC=ON

      - name: Run MakeFile
        run: make
        working-directory: build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'build/doc/html/'

  deploy:
    if: github.event_name != 'pull_request'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
