name: CI build wheels

on:
  # Run on push/merge to master
  push:
    branches:
      - master
      - build_wheels
  workflow_dispatch:  # Allow to trigger the workflow manually

jobs:
  build_wheels:
    uses: ./.github/workflows/reusable_build_wheels.yml
    with:
      container_registry: ghcr.io
      matrix_json: >-
        [
          {"os":"ubuntu-24.04","system_type":["manylinux","_2_28"],"arch":"x86_64","py_minors":"8,14"},
          {"os":"ubuntu-24.04","system_type":["musllinux","_1_2"],"arch":"x86_64","py_minors":"8,14"},
          {"os":"ubuntu-24.04","system_type":["manylinux","2014"],"arch":"i686","py_minors":"10,14"},
          {"os":"ubuntu-24.04","system_type":["musllinux","_1_2"],"arch":"i686","py_minors":"9,11"},
          {"os":"windows-2022","system_type":["win",""],"arch":"amd64","py_minors":"8,14"},
          {"os":"macos-14","system_type":["macosx",""],"arch":"arm64","py_minors":"8,14","deployment-target":"11.0"}
        ]
