name: CI Static code analysis

on: [push]

jobs:
  ci_static_analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: |
        git submodule init
        git submodule update

    - name: Install dependencies
      run: |
        sudo apt-get install cppcheck

    - name: Show cppcheck version
      run: |
        cppcheck --version

    - name: Run static code analysis
      run: |
        # We ignore src/utils/tests/test_tgen.c due to a strange bug in the
        # version of cppcheck in ubuntu-20.04
        cppcheck . --language=c -q --force --error-exitcode=2 --inline-suppr -i src/utils/tests/test_tgen.c
