name: CI tests

# This CI builds DLite and runs (almost) all tests.

# TODO:
# - Generate random passwords for the services and save them in
#   environment variables using `openssl rand -base64 12`
# - Enable the postgres and mongo services and update tests to use them.

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      #postgres:
      #  image: postgres:15
      #  ports:
      #    - 5432:5432
      #  options: >-
      #    -e POSTGRES_USER=user
      #    -e POSTGRES_PASSWORD=pgpass
      #    -e POSTGRES_DB=db

      #mongo:
      #  image: mongo:latest
      #  ports:
      #    - 27017:27017
      #  options: >-
      #    -e MONGO_INITDB_ROOT_USERNAME=user
      #    -e MONGO_INITDB_ROOT_PASSWORD=mongopass
      #    -e MONGO_INITDB_ROOT_DB=db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #- name: Add pgconf.h file
      #  run: |
      #    cat <<EOF > storages/python/tests-c/pgconf.h
      #    #define HOST "localhost"
      #    #define USER "user"
      #    #define DATABASE "db"
      #    #define PASSWORD "pgpass"
      #    EOF

      - name: Log in to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests inside the container
        run: |
          docker run --rm \
            --volume $PWD:/io \
            --network=host \
            ghcr.io/sintef/dlite/ubuntu_x86_64:latest
