name: CI tests2

# This CI builds DLite and runs (almost) all tests.
#
# The following plugins are not tested here, since they depend on an external service:
#
# Protocol plugins:
#   - sftp
#
# Storage plugins:
#   - postgresql
#   - mongodb
#   - redis
#
# Please remember to update respective plugin docstring if this list changes.
#

on:
  push:
  #pull_request:

jobs:
  newtest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/sintef/dlite/ubuntu_x86_64:latest

    steps:
      - name: Run tests inside container
        run: bash /tmp/build_and_test.sh
