name: CI tests

# This CI builds DLite and runs (almost) all tests.
#
# The following plugins are not tested here, since they depend on an external service:
#
# Protocol plugins:
#   - sftp
#
# Storage plugins:
#   - postgresql
#   - mongodb
#   - redis
#
# Please remember to update respective plugin docstring if this list changes.
#

# TODO: Split jobs from configure, then build, then package, install etc
# TODO: Windows builds: Native using VS (MSVCRT & UCRT libraries), Native using VS plus Anaconda, MingW, CYGWIN, Cross compiled with MingW on Ubuntu, Cross compiled on ? as 32bit (i686)?
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests inside the container
        run: |
          docker run \
            --volume $PWD:/io \
            --network=host \
            ghcr.io/sintef/dlite/ubuntu_x86_64:latest
