name: Cross-compile for Windows

# This workflow takes too long - run it on pull request, push to master and nightly
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'  # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get docker version
      run: docker --version

    - name: Build docker image
      run: docker build -t dlite-mingw -f Dockerfile-mingw .
