name: Cross-compile for Windows

# This workflow takes too long - run it nightly instead on every push
#on: [push]
on:
  schedule:
    - cron: '0 2 * * *'  # run at 2 AM UTC

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get docker version
      run: docker --version

    - name: Build docker image
      run: docker build -t dlite-mingw -f Dockerfile-mingw .
