name: Build a Python Wheel on Windows

on: [push]

jobs:
  msvc:
    name: Build dlite with MS Visual Studio and package a wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [windows-2019, windows-latest]
        #python-version: [ '3.8', '3.9' ]
        os: [windows-2019]
        python-version: ['3.9']

    steps:
    - name: Fetch Sources
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install SWIG
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install swig -y

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'

    - name: Prepare MSVC
      uses: bus1/cabuild/action/msdevshell@v1

    - name: Install Numpy and Wheel
      run: pip install numpy wheel

    - name: build the wheel
      run: cd python && python setup.py bdist_wheel

    - name: Install via setup.py and test the installation
      run: |
         cd python
         python setup.py install
         cd ../bindings/python/tests
         python __main__.py
